//-------------------------------------------------------------------
// マクロ名: mucom_vdat_b2t.mac
// 機能    ：MUCOM88の音色フォーマットをバイナリ型からテキスト型に変換
// 製作者  ：@overgo
//
// 使用方法：バイナリ型フォーマットの音色番号が書かれた行で実行。
//           変換されたテキスト型のフォーマットはクリップボードに保存される。
//
// 動作確認 :Windows10 Home，秀丸エディタ Ver 9.47 64bit Edition
//           MUCOM88 for Windows 2020/03/15リリース版
// 更新履歴 : 2026/04/28 Ver 1.00  初版公開
//-------------------------------------------------------------------
    call _DEBUG "【音色フォーマットの変換を開始。（バイナリ→テキスト）】";

    // テキスト型パラメータのインデックス
    #TXT_AR = 0;
    #TXT_DR = 1;
    #TXT_SR = 2;
    #TXT_RR = 3;
    #TXT_SL = 4;
    #TXT_TL = 5;
    #TXT_KS = 6;
    #TXT_ML = 7;
    #TXT_DT = 8;
    #TXT_VNAME = 9;
    #TXT_FB = 0;
    #TXT_AL = 1;

    // バイナリ型パラメータのインデックス
    #BIN_DTML = 0;
    #BIN_TL   = 1;
    #BIN_KSAR = 2;
    #BIN_AMDR = 3;
    #BIN_SR   = 4;
    #BIN_SLRR = 5;

    // 各スロットをレジスタ順に並べておく
    #BinOpIdx[0] = 0; // op1
    #BinOpIdx[1] = 2; // op3
    #BinOpIdx[2] = 1; // op2
    #BinOpIdx[3] = 3; // op4

    // メッセージおよびデバッグ用のマクロ名およびバージョン
    $MacName = "mucom_vdat_b2t.mac (v1.00)";

    // 音色番号が記述された行を取得
    #LineNo = y + 1;
    $Line = getlinetext( #LineNo );

    // 音色指定の記述を簡易チェック
    #Pos = strstr( $Line, "  @" );
    if( 0 > #Pos )
    {
        $ErrMsg = "音色番号の記述が見つかりません。\n\"@\" がある行でマクロを実行してください。";
        call _DEBUG $ErrMsg;
        message $ErrMsg, $MacName, 0x10;
    }

    // "@" の後ろが "%" でなければバイナリ型ではない
    #Pos = strstr( $Line, "@" );
    $Chk = midstr( $Line, #Pos + 1, 1 );
    if( "%" != $Chk )
    {
        //$ErrMsg = "バイナリ型の音色フォーマットを指定してください。";
        //call _DEBUG $ErrMsg;
        //message $ErrMsg, $MacName, 0x10;
		
		// テキスト→バイナリの変換マクロを呼び出す
		execmacro "mucom_vdat_t2b.mac";

		// 戻ってきたら終了
        endmacro;
    }

    // コメント部分を含めて音色名を取得（";"以降）
    $VcName = "";
    #CmmPos = strstr( $Line, ";" );
    if( 0 <= #CmmPos )
    {
        $VcName = midstr( $Line, #CmmPos + 1 );

        // コメントと前後の余白を削除
		call _DelCmmSub $VcName;
		$VcName = $$return;
        call _TrmSub $VcName;
        $VcName = $$return;

		// 音色名は最大6バイト
		$VcName = leftstr( $VcName, 6 );
        call _DEBUG "音色名を取得。(" + $VcName + ")";
    }

    // 音色番号を取得( @%は除く )
    // コメント部分の切り捨て
    call _DelCmmSub $Line;
    $Line = $$return;

    // 前後の余白を削除
    call _TrmSub $Line;
    $Line = $$return;

    // "@%" から後ろを残す
    #AtPos = strstr( $Line, "@%" );
    if( 0 > #AtPos )
    {
        $ErrMsg = "音色番号の取得に失敗しました。";
        call _DEBUG $ErrMsg;
        message $ErrMsg, $MacName, 0x10;
        endmacro;
    }

    $VoiceNo = midstr( $Line, #AtPos + 2 );
    call _TrmSub $VoiceNo;
    $VoiceNo = $$return;

    call _DEBUG "音色番号を取得。(" + $VoiceNo + ")";

    //========================================
    // バイナリ型パラメータの取得
    //========================================

	// パラメータ種別にデータを取得
	#Cnt = 0;
	while( #Cnt < 6 )
	{
		#LineNo = #LineNo + 1;
		$Line = getlinetext( #LineNo );
		call _DelCmmSub $Line;
		$Line = $$return;
		
		#ParNum = split( $VoiceDat[#Cnt], $Line, "," );
		if( #ParNum != 4 )
		{
			$ErrMsg = str( #LineNo ) + "行目、記述されているパラメータ数が異常です。("+ str() +")";
			call _DEBUG $ErrMsg;
			message $ErrMsg, $MacName, 0x10;
			endmacro;
		}
	
		call _DEBUG $Line;
		#Cnt = #Cnt + 1;
	}

	// FB/ALを取得
	#LineNo = #LineNo + 1;
	$Line = getlinetext( #LineNo );
	call _DelCmmSub $Line;
	$Line = $$return;

	// 16進数から10進数に変換
	call _Hex2DecSub $Line;
	#FbAl = ##return;
	call _DEBUG $Line;


	//========================================
	// 各パラメータをテキスト型に変換していく
	//========================================

	// 音色番号を結合
	$TxtDat = "  @" + $VoiceNo + ":{\n";

	// FB/ALを分割
	#Fb = (#FbAl / 8) & 0x07;
	#Al = #FbAl & 0x07;

	//$Line = sprintf( "  %02s, %02s\n", str( #Fb ), str( #Al ) );
	$Line = sprintf( "  %2d, %2d\n", #Fb, #Al );
	$TxtDat = $TxtDat + $Line;
	call _DEBUG $Line;

	// テキスト型のスロット順に取得
	#Cnt = 0;
	while( #Cnt < 4 )
	{
		$Str = $VoiceDat[#BIN_DTML][ #BinOpIdx[#Cnt] ];
		call _Hex2DecSub $Str;
		#Val = ##return;
		#Dt = (#Val / 16) & 0x07;
		#Ml = #Val & 0x0F;


		$Str = $VoiceDat[#BIN_TL  ][ #BinOpIdx[#Cnt] ];
		call _Hex2DecSub $Str;
		#Val = ##return;
		#Tl = #Val & 0x7F;
		
		$Str = $VoiceDat[#BIN_KSAR][ #BinOpIdx[#Cnt] ];
		call _Hex2DecSub $Str;
		#Val = ##return;

		#Ks = (#Val / 64) & 0x03;
		#Ar = #Val & 0x1F;
		
		$Str = $VoiceDat[#BIN_AMDR][ #BinOpIdx[#Cnt] ];
		call _Hex2DecSub $Str;
		#Val = ##return;
		#Am = (#Val / 128) & 0x01;
		#Dr = #Val & 0x1F;

		$Str = $VoiceDat[#BIN_SR  ][ #BinOpIdx[#Cnt] ];
		call _Hex2DecSub $Str;
		#Val = ##return;
		#Sr = #Val & 0x1F;
		
		$Str = $VoiceDat[#BIN_SLRR][ #BinOpIdx[#Cnt] ];
		call _Hex2DecSub $Str;
		#Val = ##return;
		#Sl = (#Val / 16) & 0x0F;
		#Rr = #Val & 0x0F;
		
		$Line = sprintf( "  %2d, %2d, %2d, %2d, %2d,%3d, %2d, %2d, %2d",
                            #Ar, #Dr, #Sr, #Rr, #Sl,#Tl, #Ks, #Ml, #Dt );

		if( #Cnt < 3 )
		{
			// OP1～OP3は改行のみ結合
			$TxtDat = $TxtDat + $Line + "\n";
		}
		else
		{
			// OP4の行には音色名も付加する
			$TxtDat = $TxtDat + $Line + ", \"" + $VcName + "\"}" + "\n";
		}

		#Cnt = #Cnt + 1;
	}

    setclipboard $TxtDat;
    $Msg = "クリップボードにコピーしました。\n\n" + $TxtDat;
    call _DEBUG $Msg;
    message $Msg;

    call _DEBUG "【マクロ終了】";

    endmacro;

//================================================================================

//****************************************
// 16進数から10進数に変換
//
//  call _Hex2DecSub $$1;
//           $$1 $付きの16進数の文字列
//
// 戻り値：
//     ##return; 変換後の10進数
//****************************************
_Hex2DecSub:
{
	// 前後の余白を削除
	call _TrmSub $$1;
	 $$HexStr = $$return;

	// 接頭辞を "0x" に変更
    $$HexStr = strreplace($$HexStr, "$", "" );
	$$HexStr = "0x" + $$HexStr;

	// 10進数に変換
	##Val = val( $$HexStr );
    return( ##Val );
}

//****************************************
//   MMLに記述されたコメント部分を削除
//
//  call __DelCmmSub $$1;
//
// 引数１：$$1 プレーン化する文字列
//
// 戻り値：$$SrcStr
//     コメントその他を消去した文字列
//****************************************
_DelCmmSub:
{
    // 入力された文字列を取得
    $$SrcStr = $$1;

    // コメント部分を消去
    ##ComtPos = strstr($$SrcStr, ";");
    if( 0 <= ##ComtPos ) $$SrcStr = midstr($$SrcStr, 0, ##ComtPos);

    // 余計な文字データを削除してプレーン化
    // ※空白は音色名に影響するため削除しない
    $$SrcStr = strreplace($$SrcStr, ":",  "" );
    $$SrcStr = strreplace($$SrcStr, "{",  "" );
    $$SrcStr = strreplace($$SrcStr, "}",  "" );

    // タブと改行も削除
    $$SrcStr = strreplace($$SrcStr, "\t", "" );
    $$SrcStr = strreplace($$SrcStr, "\r", "" );
    $$SrcStr = strreplace($$SrcStr, "\n", "" );
    return $$SrcStr;
}

//****************************************
// 前後の余白を削除
//
//  call _TrmSub $$1;
//           $$1 前後に余白がある文字列
//
// 戻り値：
//     $$return; 前後の余白を削除後の文字列
//****************************************
_TrmSub:
{
    $$RetStr = $$1;

    // 前方（左）の余白を削除
    call _LTrmSub( $$RetStr );
    $$RetStr = $$return;

    // 後方（右）の余白を削除
    call _RTrmSub( $$RetStr );
    $$RetStr = $$return;      // 返値を取得

    // 余白を削除後の文字列を返して終了
    return( $$RetStr );
}

//****************************************
// 前方（左）の余白を削除
//
//  call _LTrmSub $$1;
//           $$1 左に余白がある文字列
//
// 戻り値：
//     $$return; 前方の余白を削除後の文字列
//****************************************
_LTrmSub:
{
    $$InStr  = $$1; // 入力文字を取得
    while( ( " " == leftstr( $$InStr , 1 ) )&&( 0 != strlen( $$InStr ) ) )
    {
        $$InStr = rightstr( $$InStr , strlen( $$InStr ) - 1 );
    }

    return( $$InStr );
}

// ****************************************
// 後方（右）の余白を削除
//
//  call _RTrmSub $$1;
//           $$1 右に余白がある文字列
//
// 戻り値：
//     $$return; 後方の余白を削除後の文字列
// ****************************************
_RTrmSub:
{
    $$InStr  = $$1; // 入力文字を取得
    while( ( " " == rightstr( $$InStr , 1 ) )&&( 0 != strlen( $$InStr ) ) )
    {
        $$InStr = leftstr( $$InStr , strlen( $$InStr ) - 1 );
    }

    return( $$InStr );
}

// ****************************************
// デバッグ情報の出力
//
//  call _DEBUG $$1;
//           $$1 デバッグメッセージ（改行なし）
//
// 戻り値：
//     なし
// ****************************************
_DEBUG:
{
    debuginfo 2; // 「アウトプット枠にも出力」
    // [YYYY/MM/DD hh:mm:ss] (macro_filename) message
    $$Mes = "[" + year + "/" + month + "/" + day + " " + time + "](" + $MacName + ") " + $$1 + "\x0a";

    // OutputDebugStringによるメッセージの送信
    debuginfo $$Mes;
    debuginfo 0;
    return;
}
